# 08 - Exercicio Estatistico: Matriz de Notas

## Objetivo
Aplicar os conceitos estudados para analisar uma matriz de notas.

## Contexto
Uma turma com 3 alunos e 3 disciplinas possui as seguintes notas:

|            | Matematica | Python | Estatistica |
|------------|------------|--------|-------------|
| Aluno 1    | 8          | 9      | 7           |
| Aluno 2    | 6          | 8      | 9           |
| Aluno 3    | 10         | 7      | 8           |

## Tarefas
1. Construir a matriz de notas com NumPy.
2. Calcular a media por aluno (linha).
3. Calcular a media por disciplina (coluna).
4. Identificar a maior e a menor nota.
5. Calcular o desvio padrao por aluno e por disciplina.
6. Calcular a media geral da turma.
7. Identificar o aluno com a maior media.
8. Identificar a disciplina com a maior media.
9. Calcular a correlacao entre as disciplinas.
10. Normalizar as notas (z-score) por disciplina.

## Conceitos aplicados
- Criacao de arrays 2D.
- Operacoes por eixo com `axis`.
- Funcoes estatisticas: `mean`, `std`, `max`, `min`.
- Indexacao para recuperar posicoes.
- `np.corrcoef` para correlacao.
- Broadcasting para normalizacao.

## Tarefa 1 - Construir a matriz de notas
Criamos listas auxiliares com os nomes dos alunos e das disciplinas para
facilitar a interpretacao dos resultados. A matriz `notas` tem shape `(3, 3)`:
linhas = alunos, colunas = disciplinas.

In [2]:
import numpy as np

# 1. Matriz de notas
alunos = ["Aluno 1", "Aluno 2", "Aluno 3"]
disciplinas = ["Matematica", "Python", "Estatistica"]

notas = np.array([[8, 9, 7],
                  [6, 8, 9],
                  [10, 7, 8]])

print("Matriz de notas:\n", notas)
print("Shape:", notas.shape)

Matriz de notas:
 [[ 8  9  7]
 [ 6  8  9]
 [10  7  8]]
Shape: (3, 3)


## Tarefa 2 - Media por aluno (linha)
Usamos `mean(axis=1)` para reduzir cada linha (aluno) a um unico valor.
O `zip` com a lista `alunos` permite imprimir de forma legivel.

In [3]:
# 2. Media por aluno (linha)
media_aluno = notas.mean(axis=1)
print("\nMedia por aluno:")
for nome, m in zip(alunos, media_aluno):
    print(f"  {nome}: {m:.2f}")


Media por aluno:
  Aluno 1: 8.00
  Aluno 2: 7.67
  Aluno 3: 8.33


## Tarefa 3 - Media por disciplina (coluna)
Agora usamos `mean(axis=0)` para reduzir cada coluna (disciplina).
O eixo `0` percorre as linhas, agregando os valores de cada coluna.

In [4]:
# 3. Media por disciplina (coluna)
media_disc = notas.mean(axis=0)
print("\nMedia por disciplina:")
for nome, m in zip(disciplinas, media_disc):
    print(f"  {nome}: {m:.2f}")


Media por disciplina:
  Matematica: 8.00
  Python: 8.00
  Estatistica: 8.00


## Tarefa 4 - Maior e menor nota
`max()` e `min()` retornam os valores extremos. Para descobrir **onde**
eles estao usamos `argmax`/`argmin` combinados com `np.unravel_index`,
que converte o indice linear em coordenadas `(linha, coluna)`.

In [5]:
# 4. Maior e menor nota
maior = notas.max()
menor = notas.min()
print("\nMaior nota:", maior)
print("Menor nota:", menor)

# Posicoes
pos_max = np.unravel_index(np.argmax(notas), notas.shape)
pos_min = np.unravel_index(np.argmin(notas), notas.shape)
print("Maior nota em:", alunos[pos_max[0]], "-", disciplinas[pos_max[1]])
print("Menor nota em:", alunos[pos_min[0]], "-", disciplinas[pos_min[1]])


Maior nota: 10
Menor nota: 6
Maior nota em: Aluno 3 - Matematica
Menor nota em: Aluno 2 - Matematica


## Tarefa 5 - Desvio padrao por aluno e por disciplina
Passamos `ddof=1` para usar o desvio padrao **amostral** (denominador `n-1`),
em vez do populacional (padrao do NumPy). Aplicamos `axis=1` para alunos
e `axis=0` para disciplinas.

In [6]:
# 5. Desvio padrao por aluno e por disciplina
std_aluno = notas.std(axis=1, ddof=1)
std_disc = notas.std(axis=0, ddof=1)
print("\nDesvio padrao por aluno:")
for nome, s in zip(alunos, std_aluno):
    print(f"  {nome}: {s:.4f}")
print("Desvio padrao por disciplina:")
for nome, s in zip(disciplinas, std_disc):
    print(f"  {nome}: {s:.4f}")


Desvio padrao por aluno:
  Aluno 1: 1.0000
  Aluno 2: 1.5275
  Aluno 3: 1.5275
Desvio padrao por disciplina:
  Matematica: 2.0000
  Python: 1.0000
  Estatistica: 1.0000


## Tarefa 6 - Media geral da turma
Sem passar `axis`, `mean()` reduz todos os elementos a um unico valor:
a media geral considerando todas as notas.

In [7]:
# 6. Media geral
print("\nMedia geral da turma:", round(notas.mean(), 4))


Media geral da turma: 8.0


## Tarefa 7 - Aluno com maior media
Usamos `argmax` sobre o vetor `media_aluno` para obter o **indice** do
melhor aluno e, em seguida, indexamos a lista `alunos` para pegar o nome.

In [8]:
# 7. Aluno com maior media
idx_melhor_aluno = np.argmax(media_aluno)
print("\nAluno com maior media:", alunos[idx_melhor_aluno],
      f"({media_aluno[idx_melhor_aluno]:.2f})")


Aluno com maior media: Aluno 3 (8.33)


## Tarefa 8 - Disciplina com maior media
Mesma ideia da tarefa anterior, agora sobre o vetor `media_disc`.

In [9]:
# 8. Disciplina com maior media
idx_melhor_disc = np.argmax(media_disc)
print("Disciplina com maior media:", disciplinas[idx_melhor_disc],
      f"({media_disc[idx_melhor_disc]:.2f})")

Disciplina com maior media: Matematica (8.00)


## Tarefa 9 - Correlacao entre disciplinas
`np.corrcoef` calcula a matriz de correlacao. Com `rowvar=False`,
cada **coluna** e tratada como uma variavel (disciplina) e cada linha
como uma observacao (aluno). O resultado e uma matriz `3x3` simetrica
com `1.0` na diagonal.

In [10]:
# 9. Correlacao entre disciplinas
print("\nMatriz de correlacao entre disciplinas:")
print(np.round(np.corrcoef(notas, rowvar=False), 4))
print("Disciplinas:", disciplinas)


Matriz de correlacao entre disciplinas:
[[ 1.  -0.5 -0.5]
 [-0.5  1.  -0.5]
 [-0.5 -0.5  1. ]]
Disciplinas: ['Matematica', 'Python', 'Estatistica']


## Tarefa 10 - Normalizacao z-score por disciplina
Para cada disciplina subtraimos a media e dividimos pelo desvio padrao.
O broadcasting cuida de alinhar automaticamente o vetor de medias/desvios
com as colunas da matriz de notas.

In [11]:
# 10. Normalizacao z-score por disciplina
media = notas.mean(axis=0)
desvio = notas.std(axis=0, ddof=1)
notas_norm = (notas - media) / desvio
print("\nNotas normalizadas (z-score) por disciplina:\n",
      np.round(notas_norm, 4))


Notas normalizadas (z-score) por disciplina:
 [[ 0.  1. -1.]
 [-1.  0.  1.]
 [ 1. -1.  0.]]


## Resumo final
Consolidamos os principais resultados em um unico bloco, usando os
valores ja calculados nas tarefas anteriores.

In [12]:
# Resumo final
print("\nResumo:")
print("  Media por aluno:", np.round(media_aluno, 2))
print("  Media por disciplina:", np.round(media_disc, 2))
print("  Maior nota:", maior)
print("  Menor nota:", menor)
print("  Desvio por aluno:", np.round(std_aluno, 4))
print("  Desvio por disciplina:", np.round(std_disc, 4))


Resumo:
  Media por aluno: [8.   7.67 8.33]
  Media por disciplina: [8. 8. 8.]
  Maior nota: 10
  Menor nota: 6
  Desvio por aluno: [1.     1.5275 1.5275]
  Desvio por disciplina: [2. 1. 1.]
